name: Giaborep
favicon: null
layout_spectrum: 0.08959
typography_spectrum: 0.66692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ca1a1a'
    - '#3f2d21'
    - '#fffefb'
    - '#2d9d62'
    - '#c6b9a8'
  brandStrength: 0.3125
  lightness: 0.9798818272538483
  saturation: 0.28086344595067203
  rhythmicContrast: 0.30503849615342915
purpose: []
